name: theme

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  core:
    path: ../../../core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
