name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  elementary: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^11.1.4
  hive: ^2.2.3
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^4.4.1


dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
