name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  elementary: ^3.0.0
  flutter_feature_arch:
    git:
      url: https://github.com/ERGataullin/flutter_feature_arch.git
  go_router: ^11.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
