name: _
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - app
  - core
  - features/common/auth
  - features/common/movies
  - features/common/root_menu
  - features/shared/cookie_manager
  - features/shared/l10n
  - features/shared/player
  - features/shared/theme

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  core:
    path: core
  cookie_manager:
    path: features/shared/cookie_manager
  l10n:
    path: features/shared/l10n
  player:
    path: features/shared/player
  theme:
    path: features/shared/theme

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
