name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - app
  - core
  - features/common/auth
  - features/common/movies
  - features/common/root_menu
  - features/shared/cookie_manager
  - features/shared/l10n
  - features/shared/player
  - features/shared/theme
dependencies:
  web: ^1.1.0
