name: player

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  core:
    path: ../../../core
  flutter:
    sdk: flutter
  l10n:
    path: ../../shared/l10n
  theme:
    path: ../../shared/theme
  video_player: ^2.9.2
  web:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
