name: player

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
  l10n:
  theme:

  video_player:
  web:

dev_dependencies:
  flutter_native_splash: ^2.4.4
