arb-dir: assets/localizations
output-dir: lib/src/utils/localizations
template-arb-file: ru.arb
output-localization-file: localizations.g.dart
output-class: PlayerLocalizations
synthetic-package: false
nullable-getter: false
