name: player
description: A player module library of AniWay.
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  core: 
    path: ../../core
  flutter:
    sdk: flutter
  video_player: ^2.8.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
