name: core

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations:
  elementary:
  hive:
  html:
  http:
  intl:
  path_provider:
  provider:
  url_launcher:

flutter:
  fonts:
    - family: Alvida
      fonts:
        - asset: assets/fonts/alvida.ttf
