name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auth:
    path: ../modules/auth
  core: 
    path: ../core
  elementary: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^12.1.0
  hive: ^2.2.3
  menu:
    path: ../modules/menu
  movies: 
    path: ../modules/movies
  path_provider: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
