name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auth:
    path: ../features/common/auth
  cookie_manager: 
    path: ../features/shared/cookie_manager
  core: 
    path: ../core
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.3
  l10n:
    path: ../features/shared/l10n
  movies: 
    path: ../features/common/movies
  player:
    path: ../features/shared/player
  root_menu:
    path: ../features/common/root_menu
  theme:
    path: ../features/shared/theme
  web: ^1.0.0

dev_dependencies:
  flutter_lints:
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
