name: app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  auth:
    path: ../features/common/auth
  flutter:
    sdk: flutter
  go_router: ^14.6.3
  movies:
    path: ../features/common/movies
  root_menu:
    path: ../features/common/root_menu

dev_dependencies:
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
