name: app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  auth:
  cookie_manager:
  core:
  l10n:
  movies:
  player:
  root_menu:
  theme:

  go_router:
  web:

dev_dependencies:
  flutter_native_splash:

flutter:
  uses-material-design: true
