name: auth
description: An auth module library of AniWay.
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  core: 
    path: ../../core
  flutter:
    sdk: flutter
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  generate: true
  uses-material-design: true
